# Site settings
title: "MyResume"
description: "A resume built from template for Jekyll and GitHub Pages sites."
url: "https://singhaidotnish.github.io"
baseurl: "/myresume"
repository: "singhaidotnish/myresume"
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nishith Singhai"
resume_title:                   "Sr Pipeline TD"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "singhai.nish@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9029-555541"
resume_contact_address:         "302 Jigna Arcade Navi Mumbai"

resume_header_contact_info:     "302 Jigna Arcade Navi Mumbai • 400 709 • singhai.nish@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Objective is to develop methods and tools that richly integrate the capabilities of people and machines in efforts to produce film, animation. To combine skills and deep understanding of processes, data management, programming, and human-computer interaction to enable effective means for tight collaboration on projects of any scale. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/singhaidotnish/"
  resume_linkedin_url:          "https://www.linkedin.com/in/singhaidotnish"
  resume_website_url:          "https://singhaidotnish.github.io/myresume"

resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

# Ensure Jekyll processes all files
include:
  - ".htaccess"
  - "_redirects"
  - "CNAME"
  - "robots.txt"
  - "sitemap.xml"
  - "assets"
  - "static"

# Ensure Jekyll doesn't ignore important folders
keep_files:
  - assets
  - static
  - images

# Disable Jekyll strict mode (useful for missing files)
strict_front_matter: false

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

### Phantom settings
footer_text: '© 2018 Nishith Singhai'
admin_name: 'Nishith Singhai'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
