name: Jekyll Build

on:
  push:
    branches:
      - main  # Trigger on changes to main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby & Install Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Jekyll
        run: gem install jekyll

      - name: Install Jekyll Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Clean & Build Jekyll
        run: |
          rm -rf _site .jekyll-cache
          JEKYLL_ENV=production bundle exec jekyll build --trace

      - name: Verify _site directory after build
        run: ls -la _site

      - name: Upload built Jekyll site
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site
          retention-days: 30  # Keep the artifact for 5 days
