name: Jekyll Build & Deploy

on:
  push:
    branches:
      - gh-pages  # Change if using 'main' or another branch
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Use the Ruby version required by Jekyll
          bundler-cache: true  # Caches gems automatically

      - name: Unset Bundler Deployment Mode
        run: bundle config unset deployment

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # Deploy to gh-pages, but source must be another branch
